name: Continuous Integration
on: push

jobs:
    phpstan:
        name: PHPStan
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.5'
            - name: Install dependencies
              run: composer update
            - name: Run PHPStan
              run: vendor/bin/phpstan analyse

    phpunit:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php: [ '8.4', '8.5' ]
                prefer-lowest: [ '', '--prefer-lowest' ]
        steps:
            - uses: actions/checkout@v4
            - uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
            - name: Install dependencies
              run: composer update -n --prefer-dist  ${{ matrix.prefer-lowest }}
            - name: Run PHPUnit unit tests
              run: vendor/bin/phpunit

    coding_standards:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.5'
            - name: Install dependencies
              run: composer update
            - name: Run PHP-CS-Fixer
              run: vendor/bin/php-cs-fixer fix --dry-run -v

    check-licenses:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.5'
            - name: Install dependencies
              run: composer update
            - name: Run License Checker
              run: bin/license-checker check --quiet
